---
title: "Map_Function"
output: html_notebook
---

## Multiple Arguements with Map Function

## Getting Started

```{r, eval = FALSE}

## Getting Started 

# Create a list n containing the values: 5, 10, and 20
n = list(5,10,20)


# Call map() on n with rnorm() to simulate three samples

map(n, rnorm)


```

## Mapping over two Arguements

```{r, eval= FALSE}

# Initialize n
n <- list(5, 10, 20)

# Create a list mu containing the values: 1, 5, and 10

mu= list(1,5,10)

# Edit to call map2() on n and mu with rnorm() to simulate three samples
map2(n,mu, rnorm)

````


## Mapping over more than two Arguements

```{r, eval = FALSE}

# Initialize n and mu
n <- list(5, 10, 20)
mu <- list(1, 5, 10)

# Create a sd list with the values: 0.1, 1 and 0.1

sd= list(0.1,1,0.1)

# Edit this call to pmap() to iterate over the sd list as well
# Name the elements of the argument list
z<-pmap(list(mean=mu, n=n, sd=sd), rnorm)

```


## Mapping over functions and their arguements

```{r, eval =FALSE}

# Define list of functions
f <- list("rnorm", "runif", "rexp")

# Parameter list for rnorm()
rnorm_params <- list(mean = 10)

# Add a min element with value 0 and max element with value 5
runif_params <- list(min = 0, max = 5)

# Add a rate element with value 5
rexp_params <- list(rate = 5)

# Define params for each function
params <- list(
  rnorm_params,
  runif_params,
  rexp_params
)

# Call invoke_map() on f supplying params as the second argument
invoke_map(f, n = 5, params)

```

## Map with Side Effects: Introducing walk()


```{r, eval = FALSE}


# Define list of functions
f <- list(Normal = "rnorm", Uniform = "runif", Exp = "rexp")

# Define params
params <- list(
  Normal = list(mean = 10),
  Uniform = list(min = 0, max = 5),
  Exp = list(rate = 5)
)

# Assign the simulated samples to sims
sims<- invoke_map(f, params, n = 50)

# Use walk() to make a histogram of each element in sims

walk(sims, hist)
```

## walk() over two or more arguements

```{r, eval = FALSE}

# Replace "Sturges" with reasonable breaks for each sample
breaks_list <- list(
  Normal = seq(6, 16, 0.5),
  Uniform = seq(0, 5, 0.25),
  Exp = seq(0, 1.5, 0.1)
)

# Use walk2() to make histograms with the right breaks

walk2(sims, breaks_list, hist)

```


## Putting together writing functions and walk

```{r, eval =FALSE}


# Turn this snippet into find_breaks()

 find_breaks<-function(x){
  rng <- range(x, na.rm = TRUE)
  seq(rng[1], rng[2], length.out = 30)
  }


# Call find_breaks() on sims[[1]]

find_breaks(sims[[1]])


## Nice breaks for All,

# Use map() to iterate find_breaks() over sims: nice_breaks

nice_breaks<- map(sims, find_breaks)

# Use nice_breaks as the second argument to walk2()
walk2(sims,nice_breaks,hist)

```

## Walking with many arguements

```{r, eval = FALSE}

# Increase sample size to 1000
sims <- invoke_map(f, params, n = 1000)

# Compute nice_breaks (don't change this)
nice_breaks <- map(sims, find_breaks)

# Create a vector nice_titles

nice_titles= c("Normal(10,1)","Uniform(0,5)","Exp(5)")

# Use pwalk() instead of walk2()
pwalk(list(x = sims, breaks = nice_breaks, main = nice_titles), hist, xlab = "")

```

## Pipe operator

```{r, eval = FALSE}

# Pipe this along to map(), using summary() as .f
sims %>%
  walk(hist) %>%map(summary)
```




























































































